

development:
  adapter: postgresql
  encoding: utf8
  database: static_development
  pool: 5
  username: postgres
  password: qwerty123

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: static_test
  pool: 5
  username: postgres
  password: qwerty123

production:
  adapter: postgresql
  encoding: utf8
  database: static_production
  pool: 5
  username: postgres
  password: qwerty123

cucumber:
  <<: *TEST
